---
  name: Release Envy CLI

  on:
    push:
      tags:
        - "*"

  jobs:
    release:
      runs-on: ubuntu-latest
      outputs:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
      steps:
        - uses: actions/checkout@v3
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            draft: true
            prerelease: false
    build:
      needs: release
      runs-on: ubuntu-latest
      strategy:
        matrix:
          platform: 
            - linux-x64
            - linux-arm64
            - windows-x64
            - darwin-x64
            - darwin-arm64
      steps:
        - uses: actions/checkout@v3
        - name: Use Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: Install dependencies
          run: bun install
        - name: Build CLI
          run: |
            bun build --compile --minify --sourcemap ./src/bin.ts --target bun-${{ matrix.platform }} --outfile ./dist/${{ matrix.platform }}
        - name: Upload build artifact to release
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.release.outputs.upload_url }}
            asset_path: ./dist/${{ matrix.platform }}
            asset_name: envy-${{ matrix.platform }}
            asset_content_type: application/octet-stream
...